name: Hardhat Tests

on: [push]

jobs:
  contract-tests:
    runs-on: ubuntu-latest
    env:
      MY_ENV_VAR: ${{ secrets.MAINNET_RPC_URL }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm i
      - name: Run Hardhat tests
        run: make test-contracts
