name: Hardhat Tests

on: [push]

jobs:
  contract-tests:
    runs-on: ubuntu-latest
    env:
      MAINNET_RPC_URL: "https://mainnet.infura.io/v3/5ffc47f65c4042ce847ef66a3fa70d4c"
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm i
      - name: Run Hardhat tests
        run: make test-contracts
